/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_12;

/**
 *
 * @author HP
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tsegitiga = new javax.swing.JButton();
        tpersegipanjang = new javax.swing.JButton();
        tpersegi = new javax.swing.JButton();
        tlingkaran = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI BANUN DATAR");

        tsegitiga.setBackground(new java.awt.Color(204, 204, 255));
        tsegitiga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tsegitiga.setText("SEGITIGA");
        tsegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsegitigaActionPerformed(evt);
            }
        });

        tpersegipanjang.setBackground(new java.awt.Color(204, 204, 255));
        tpersegipanjang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tpersegipanjang.setText("PERSEGI PANJANG");
        tpersegipanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpersegipanjangActionPerformed(evt);
            }
        });

        tpersegi.setBackground(new java.awt.Color(204, 204, 255));
        tpersegi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tpersegi.setText("PERSEGI");
        tpersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpersegiActionPerformed(evt);
            }
        });

        tlingkaran.setBackground(new java.awt.Color(204, 204, 255));
        tlingkaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tlingkaran.setText("LINGKARAN");
        tlingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlingkaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tlingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpersegipanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpersegi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tsegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tpersegipanjang)
                .addGap(10, 10, 10)
                .addComponent(tpersegi)
                .addGap(18, 18, 18)
                .addComponent(tlingkaran)
                .addGap(18, 18, 18)
                .addComponent(tsegitiga)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tpersegipanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpersegipanjangActionPerformed
        // TODO add your handling code here:
        new PERSEGI_PANJANG().setVisible(true);
        
    }//GEN-LAST:event_tpersegipanjangActionPerformed

    private void tlingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlingkaranActionPerformed
        // TODO add your handling code here:
        new LINGKARAN().setVisible(true);
    }//GEN-LAST:event_tlingkaranActionPerformed

    private void tpersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpersegiActionPerformed
        // TODO add your handling code here:
        new PERSEGI().setVisible(true);
    }//GEN-LAST:event_tpersegiActionPerformed

    private void tsegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsegitigaActionPerformed
        // TODO add your handling code here:
        new SEGITIGA().setVisible(true);
    }//GEN-LAST:event_tsegitigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tlingkaran;
    private javax.swing.JButton tpersegi;
    private javax.swing.JButton tpersegipanjang;
    private javax.swing.JButton tsegitiga;
    // End of variables declaration//GEN-END:variables
}
