/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_12;

import com.sun.jdi.DoubleValue;

/**
 *
 * @author HP
 */
public class PERSEGI_PANJANG extends javax.swing.JFrame {
    

    /**
     * Creates new form PERSEGI_PANJANG
     */
    public PERSEGI_PANJANG() {
        initComponents();
        treset();
    }
    
 void treset(){
     tpanjang.setText("");
     tlebar.setText(null);
     tluas.setText(null);
     tkeliling.setText(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tpanjang = new javax.swing.JTextField();
        tlebar = new javax.swing.JTextField();
        treset = new javax.swing.JButton();
        tkembali = new javax.swing.JButton();
        thitung = new javax.swing.JButton();
        tluas = new javax.swing.JLabel();
        tkeliling = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PERSEGI PANJANG");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("LEBAR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("PANJANG");

        tpanjang.setBackground(new java.awt.Color(204, 204, 255));
        tpanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpanjangActionPerformed(evt);
            }
        });

        tlebar.setBackground(new java.awt.Color(204, 204, 255));
        tlebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlebarActionPerformed(evt);
            }
        });

        treset.setBackground(new java.awt.Color(204, 204, 255));
        treset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_12/go-back-arrow.png"))); // NOI18N
        treset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresetActionPerformed(evt);
            }
        });

        tkembali.setBackground(new java.awt.Color(204, 204, 255));
        tkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_12/back-arrow.png"))); // NOI18N
        tkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkembaliActionPerformed(evt);
            }
        });

        thitung.setBackground(new java.awt.Color(204, 204, 255));
        thitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_12/calculator.png"))); // NOI18N
        thitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thitungActionPerformed(evt);
            }
        });

        tluas.setText("LUAS       : ");

        tkeliling.setText("KELILING :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tkeliling)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tluas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(thitung)))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(treset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(tkembali)
                                .addGap(38, 38, 38))
                            .addComponent(tlebar)
                            .addComponent(tpanjang))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tpanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(treset)
                    .addComponent(tkembali)
                    .addComponent(thitung, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(tluas)
                .addGap(18, 18, 18)
                .addComponent(tkeliling)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresetActionPerformed
        // TODO add your handling code here:
        treset();
    }//GEN-LAST:event_tresetActionPerformed

    private void thitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thitungActionPerformed
        // TODO add your handling code here:
        int panjang = Integer.parseInt(tpanjang.getText());
        int lebar = Integer.parseInt(tlebar.getText());
        int luas = panjang*lebar;
        int keliling = 2*(panjang*lebar);
        
        tluas.setText("luas =" +luas);
        tkeliling.setText("keliling =" +keliling);
    }//GEN-LAST:event_thitungActionPerformed

    private void tkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkembaliActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
    }//GEN-LAST:event_tkembaliActionPerformed

    private void tlebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlebarActionPerformed

    private void tpanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpanjangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PERSEGI_PANJANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PERSEGI_PANJANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PERSEGI_PANJANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PERSEGI_PANJANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PERSEGI_PANJANG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton thitung;
    private javax.swing.JLabel tkeliling;
    private javax.swing.JButton tkembali;
    private javax.swing.JTextField tlebar;
    private javax.swing.JLabel tluas;
    private javax.swing.JTextField tpanjang;
    private javax.swing.JButton treset;
    // End of variables declaration//GEN-END:variables
}
